server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/auth/**
        - id: payment-service
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/api/payments/**
        - id: event-service
          uri: lb://EVENTSERVICE
          predicates:
            - Path=/api/events/**
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwkse

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: qR7WmcTJvYskp6Kw9AEG4dLzBnXh2U3R

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.eventify.ApiGateway.security.JwtAuthenticationFilter: DEBUG
